# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_photo',
        ),
        migrations.AddField(
            model_name='artistimages',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Artist'),
        ),
    ]
