# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0003_venuelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='event',
            name='requestor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='bookr.Artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='bookr.VenueList'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='bookr.Event'),
        ),
        migrations.AlterField(
            model_name='venueimages',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.VenueList'),
        ),
        migrations.AlterField(
            model_name='venuelist',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
