# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 01:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0004_auto_20170328_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venueimages',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_image', to='bookr.VenueList'),
        ),
    ]
